### ISSUE TITLE
Why not use Runnable/Callable constructor to bind runtime context？

### ISSUE THREAD

**Issue by Sirius-LiXiaoQi** [alibaba/transmittable-thread-local#187]
Why don't we intercept the class through JVMTI and find that the parent class contains the runnable / callable interface, so we add a member variable for the reference context. The constructor constructs and completes the reference context. When calling the run method, the context is loaded

**Comment by Sirius-LeeFeng** [comment]
l noticed  that "myRunnableA { logicBefore; myRunnableB; logicAfter; }" #135 

If this is the case, why don't we define a RunnableA, RunnableB private deep copy Context, don't bind to the thread Context, and work directly on the respective Context every time you get/set

**Comment by Sirius-LeeFeng** [comment]
I've learned that the extension constructor statics the context, and execute/ Submit is the correct point to load the context (scene: Runnable/Callable reused)

**Comment by oldratlee** [comment]
> intercept the class through JVMTI and find that the parent class contains the runnable / callable interface, 
> so we add a member variable for the reference context

This is a good technical mean that able to enhance all `runnable / callable` instances.

Because `runnable / callable` interface is very universal, they maybe used in non-async environments;
So "enhance **_all_** instances", this mean maybe overkill.  @Sirius-LiXiaoQi 
Presently `TTL` enhance executors(eg: `ExecutorService`/`ForkJoinPool `) so as to avoid the **overkill**.

Or as @Sirius-LeeFeng said, "`execute`/`submit` is the correct point to load the context".
\# a **better** explanation for **overkill** or `interception point` ♥️👍
